version: '3.9'

services:
  db:
    container_name: postgres
    hostname: postgres
    image: postgres:14.2-alpine3.15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "my_bar"
    ports:
      - "5433:5432"
    expose:
      - 5433
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    image: my-bar-backend:latest
    container_name: my-bar-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    expose:
      - 8089
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
    depends_on:
      - db
volumes:
  postgres-data: