server:
  servlet:
    contextPath: /api/bar
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_bar_db?autoReconnect=true&useSSL=false
    username: root
    password: check001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    fail-on-missing-locations: true

logging:
  level:
    org:
      springframework:
        security: INFO

kafka:
  bootstrap-address: localhost:9093
  events:
    rates-topic-name: my_bar_cocktails.RATED
