server:
  servlet:
    contextPath: /api/bar
  port: 8089
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:my_bar}?schema=${DATABASE_SCHEMA:public}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    fail-on-missing-locations: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    org:
      springframework:
        security: INFO

my-bar:
  events:
    rates-topic-name: my_bar_cocktails.RATED
