server:
  contextPath: /api/bar
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/my_bar_dev?autoReconnect=true&useSSL=false
    username: root
    password: check001
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org:
      springframework:
        security: DEBUG